#
# Makefile
#
# Computer Science 50
# Problem Set 6
#

minesweeper: minesweeper.c Makefile
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o minesweeper minesweeper.c -lm

clean:
	rm -f *.o core minesweeper
